-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 16:00:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `about` BLOB NULL,
  `filmcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  `film_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_order_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film_carier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_carier` (
  `film_id` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  INDEX `fk_film_carier_film_idx` (`film_id` ASC),
  INDEX `fk_film_carier_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_film_carier_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_carier_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mydb`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ganre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ganre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film_ganre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_ganre` (
  `film_id` INT NOT NULL,
  `ganre_id` INT UNSIGNED NOT NULL,
  INDEX `fk_film_ganre_film1_idx` (`film_id` ASC),
  INDEX `fk_film_ganre_ganre1_idx` (`ganre_id` ASC),
  CONSTRAINT `fk_film_ganre_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_ganre_ganre1`
    FOREIGN KEY (`ganre_id`)
    REFERENCES `mydb`.`ganre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`director` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `about` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film_director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_director` (
  `director_id` INT UNSIGNED NOT NULL,
  `film_id` INT NOT NULL,
  INDEX `fk_film_director_director1_idx` (`director_id` ASC),
  INDEX `fk_film_director_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_director_director1`
    FOREIGN KEY (`director_id`)
    REFERENCES `mydb`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_director_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actor` (
  `id` INT NOT NULL,
  `actorname` VARCHAR(255) NOT NULL,
  `about` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`film_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_actor` (
  `actor_id` INT NOT NULL,
  `film_id` INT NOT NULL,
  INDEX `fk_film_actor_actor1_idx` (`actor_id` ASC),
  INDEX `fk_film_actor_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_actor_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `mydb`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_actor_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`carrier`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`carrier` (`id`, `type`) VALUES (1, 'CD');
INSERT INTO `mydb`.`carrier` (`id`, `type`) VALUES (2, 'DVD');
INSERT INTO `mydb`.`carrier` (`id`, `type`) VALUES (3, 'BLUERAY');

COMMIT;

